### ISSUE TITLE
Starfield V1.9.51.0

### ISSUE THREAD

**Issue by Howard-Starfield** [HarukaMa/starfield-xgp-import#12]
Hello,
The tool wasn't able to import the Steam version of Starfield to XGP Starfield, it has the following error:
========== Starfield Save File Importer v0.0.5 ==========
WARNING: This tool is experimental. Always manually back up your existing saves!

Found container path: C:\Users\sdokd\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\00090000056F3DE8_0000000000000000000000007BF72399
Parsed container index:
  Package name: BethesdaSoftworks.ProjectGold_3275kfvn8vcwc!Game
  3 containers:
    Saves/Exitsave0_272CF1E8M546F6D6D79204F6C69766572_250131_20240201180900_902_22_4.sfs (26541846 bytes)
    Saves/Save6_272CF1E8M4272616E646F6E204A616D6573_290703_20240201124001_980_23_4.sfs (5819745 bytes)
    Settings/Settings (562 bytes)

Traceback (most recent call last):
  File "C:\Users\sdokd\Downloads\Starfield Backup\Import\main.py", line 132, in <module>
    main()
  File "C:\Users\sdokd\Downloads\Starfield Backup\Import\main.py", line 68, in main
    save_file = SaveFile.from_stream(source_save_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdokd\Downloads\Starfield Backup\Import\savefile_types.py", line 51, in from_stream
    raise NotSupportedError(f"unexpected value: {value} != 0x103")
utils.NotSupportedError: unexpected value: 2117091331 != 0x103

**Comment by HarukaMa** [comment]
It seems the save data format has significantly changed in the latest version. Lemme check if I can get a save from new version.

**Comment by Howard-Starfield** [comment]
Thank you for the quick respond, The following is my save, hope this can help you!

[https://drive.google.com/file/d/1Xyf02h8abxDGig7h4QmKWccKxqRSjOe_/view?usp=sharing](url)

**Comment by HarukaMa** [comment]
It seems only that one field has changed in the savefile, but the xbox side has changed and added a new field that I don't know how to generate right now. However I can still store it in the old format and let the game convert the format itself.

I can now import your save, but it took a very long time to load. Is that expected?

**Comment by Howard-Starfield** [comment]
Yes its expected because I have a ton of ship in that save =)
